apiVersion: v1
kind: Pod
metadata:
  name: foo
spec:
  containers:
    - name: foo
      image: alpine:latest
      command: ["sleep", "10000"]
      volumeMounts:
        - name: foo
          mountPath: /data
  volumes:
    - name: foo
      persistentVolumeClaim:
        claimName: foo
