apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
staticPodPath: /etc/kubernetes/manifests
address: 0.0.0.0
port: 10250
cgroupDriver: cgroufs
tlsCertFile: /etc/kubernetes/certs/kube-worker-k8s-node1.crt
tlsPrivateKeyFile: /etc/kubernetes/certs/kube-worker-k8s-node1.key
clusterDomain: cluster.local
clusterDNS:
  - 10.10.0.10
podCIDR: 10.200.0.0/16
resolvConf: /run/systemd/resolve/resolv.conf
registerNode: true
authentication:
  anonymous:
    enabled: false
  webhook:
    enabled: false
  x509:
    clientCAFile: /etc/kubernetes/certs/kube-ca.crt
authorization:
  mode: Webhook
