apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  nodeName: k8s-node3
  containers:
    - name: test
      image: nginx:alpine
      securityContext:
        capabilities:
          add:
            - NET_RAW
